filetype plugin indent on
syntax on
colorscheme torte

set number
set shiftwidth=3
set ignorecase
set autoindent
set incsearch
set lbr
set timeoutlen=0
set hidden
set splitbelow
set splitright
set expandtab

set textwidth=80

noremap k gk
noremap j gj
noremap Q <Nop>
noremap K <C-w><C-w>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

noremap <C-P> <C-b>
noremap <Tab> :bn<CR>
noremap <S-Tab> :bp<CR>

noremap <F1> <Esc>:tabp<CR>
noremap <F2> <Esc>:tabn<CR>
noremap <F5> @a
inoremap <F12> <C-R>=strftime("%Y-%m-%d %a %I:%M %p")<CR>
noremap <F12> ggg?G

set undofile
set undodir=$HOME/.vim/undo
set undolevels=1000
set undoreload=10000

set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar

if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Menlo\ Regular:h14
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif

set vb t_vb=
set noeb vb t_vb=
