[[SynthHD Pro, SetFrequencyCHBGUI, '(np.arange(-3,3+0.25,0.25)+10001)*1e6', 0.2, false,
    null, true, [[PXIe5171, UpdateSequenceAttrs, parent_info, null, false, null, true,
        []], [YagIsolator, SetNrQswitchesGUI, 10, null, false, null, true, []], [
        PXIe5171, ReadValue, null, null, true, 10, true, []], [ZaberTMM, RandomPosition,
        null, null, false, null, true, []]]]]
