[[PXIe5171, ClearBuffer, 0.1, null, true, null, true, []], [Wavelength, SetPort, [
      1, 2, 16], 5, false, null, true, []], [SynthHD Pro, SetFrequencyCHBGUI, 'np.random.permutation(np.tile(np.arange(-3,3+0.25,0.25)+10004,5)*1e6)',
    1.5, false, null, true, [[PXIe5171, UpdateSequenceAttrs, parent_info, null, false,
        null, true, []], [YagIsolator, SetNrQswitchesGUI, 10, null, false, null, true,
        []], [PXIe5171, ReadValue, null, null, true, 10, true, []]]]]
