[[PXIe5171, ClearBuffer, 0.1, null, true, null, true, []], [Wavelength, SetPort, [
      1, 2, 16], 5, false, null, true, []], [SynthHD Pro, SetPower, [-17.82, -16.9,
      -15.59, -14.59, -13.68, -11], 5, false, null, true, [[PXIe5171, UpdateSequenceAttrs,
        parent_info, null, false, null, true, []], [YagIsolator, SetNrQswitchesGUI,
        6000, null, false, null, true, []], [PXIe5171, ReadValue, null, null, true,
        6000, true, []]]]]
