[[PXIe5171, DummyFunc, null, 1, false, 80, true, [[PXIe5171, UpdateSequenceAttrs,
        parent_info, null, false, null, true, []], [YagIsolator, SetNrQswitchesGUI,
        50, null, false, null, true, []], [PXIe5171, ReadValue, null, null, true,
        50, true, []], [ZaberTMM, nextStep, null, null, false, null, true, []]]]]
