[[BK4063, SetChannel1Frequency, 'np.arange(0.25,2+0.25,0.25)*1e6', null, true, null,
    true, [[BK4063, SetOutputState2, false, null, true, null, true, []], [BK4063,
        GetFrequencyFromSequencerBasicWave2, parent_info, null, true, null, true,
        []], [SDG1032X, GetFrequencyFromSequencerBurst, parent_info, null, true, null,
        true, []], [BK4063, SetOutputState2, true, 20, true, null, true, []]]]]
