[[Laser Lock 1, SetLockPointSeed2, 'np.random.permutation(243 + np.array([-7,-7,-7,-6,-6,-6,-5,-5,-5,-4,-4,-4,-3,-3,-3,-2,-2,-1,-1,0,0,1,1,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7]))',
    5, false, null, true, [[PXIe5171, UpdateSequenceAttrs, parent_info, null, false,
        null, true, []], [PXIe5171, DummyFunc, 1, 0.1, false, 10, true, [[YagIsolator,
            SetNrQswitchesGUI, 10, null, false, null, true, []], [PXIe5171, ReadValue,
            null, null, true, 10, true, []], [ZaberTMM, RandomPosition, null, null,
            false, null, true, []]]]]]]
