[[SynthHD Pro, SetPowerCHAGUI, 'np.arange(-22,-8,2)', 1, false, null, true, [[SynthHD
          Pro, SetPowerCHBGUI, 'np.array([-15.26, -13.9, -11.71, -10.57, -9.82, -9.55,
          -9.35, -8.8])', 1, false, null, true, [[PXIe5171, UpdateSequenceAttrs, parent_info,
            null, false, null, true, []], [PXIe5171, Dummyfunc, 1, 0.01, false, 50,
            true, [[YagIsolator, SetNrQswitchesGUI, 10, null, false, null, true, []],
              [PXIe5171, ReadValue, null, null, true, 10, true, []], [ZaberTMM, RandomPosition,
                null, null, false, null, true, []]]]]]]]]
