[[PXIe5171, ClearBuffer, 0.1, null, true, null, true, []], [Wavelength, SetPort, [
      1, 2, 16], 5, false, null, true, []], [Laser Lock, SetLockPointSeed2, 'np.arange(-112,-100,1)',
    2, false, 10, true, [[PXIe5171, DummyFunc, 'np.arange(0,2,1)', null, false, null,
        true, [[ShutterControl, SetVoltage, 0, 0, false, null, true, [[PXIe5171, UpdateSequenceAttrs,
                parent_info, null, false, null, true, []], [YagIsolator, SetNrQswitchesGUI,
                25, null, false, null, true, []], [PXIe5171, ReadValue, null, null,
                true, 25, true, []], [PXIe5171, ClearBuffer, 0.1, null, true, null,
                true, []]]]]]]]]
