[[BK4063, SetChannel1Frequency, 'np.array([1.25])*1e6', null, true, null, true, [
      [BK4063, SetOutputState2, false, null, true, null, true, []], [BK4063, GetFrequencyFromSequencerBasicWave2,
        parent_info, null, true, null, true, []], [SDG1032X, GetFrequencyFromSequencerBurst,
        parent_info, null, true, null, true, []], [BK4063, SetOutputState2, true,
        null, true, null, true, []], [PXIe5171, UpdateSequenceAttrs, parent_info,
        null, false, null, true, []], [Laser Lock 1, Dummyfunc, 1, 0.1, false, 50,
        true, [[YagIsolator, SetNrQswitchesGUI, 10, null, false, null, true, []],
          [PXIe5171, ReadValue, null, null, true, 10, true, []], [ZaberTMM, RandomPosition,
            null, null, false, null, true, []]]]]]]
