COM_port:
  type: dummy
  value: client
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: true
attributes:
  column_names:
  - time
  - ch1
  - waveform1
  - frequency1
  - amplitude1
  - offset1
  - ch2
  - waveform2
  - frequency2
  - amplitude2
  - offset2
  units:
  - s
  - ''
  - ''
  - Hz
  - V
  - V
  - ''
  - ''
  - Hz
  - V
  - V
connection:
  type: dummy
  value:
    device_name: SDG1032X
    port_control: '12347'
    port_readout: '12346'
    publisher_name: LaserControl
    server: 172.28.173.180
device:
  column: 2
  constr_params:
  - driver
  - connection
  - COM_port
  correct_response: Siglent Technologies,SDG1032X,SDG1XCAD2R3284,1.01.01.30R1
  driver: NetworkingClient
  label: SDG1032X
  max_nan_count: 0
  meta_device: false
  name: SDG1032X
  path: readout
  plots_queue_maxlen: 1000
  row: 4
  slow_data: true
driver:
  type: dummy
  value: SiglentSDG1032X
dt:
  column: 1
  command: null
  label: Loop delay [s]
  row: 2
  tooltip: null
  type: QLineEdit
  value: 2
enabled:
  column: 0
  label: Device enabled
  row: 0
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 0
