[[PXIe5171, DummyFunc, 1, null, false, null, true, [[PXIe5171, DummyFunc, 1, 0.1,
        false, 100, true, [[YagIsolator, SetNrQswitchesGUI, 10, null, false, null,
            true, []], [PXIe5171, ReadValue, null, null, true, 10, true, []], [ZaberTMM,
            RandomPosition, null, null, false, null, true, []]]]]], [PXIe5171, DummyFunc,
    1, 120, false, 10, true, [[PXIe5171, DummyFunc, 1, 0.1, false, 100, true, [[YagIsolator,
            SetNrQswitchesGUI, 10, null, false, null, true, []], [PXIe5171, ReadValue,
            null, null, true, 10, true, []], [ZaberTMM, RandomPosition, null, null,
            false, null, true, []]]]]]]
