COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: COM10
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - position
  units:
  - s
  - mm
change_setpoint:
  align: nsew
  argument: setpoint_value
  column: 2
  command: SetPosition
  label: Set
  row: 5
  type: QPushButton
device:
  column: 2
  constr_params:
  - COM_port
  correct_response: 'Device 1 SN: 103239'
  driver: Zaber
  label: Zaber
  max_nan_count: 10
  meta_device: false
  name: Zaber
  path: lens_testing
  plots_queue_maxlen: 1000
  row: 1
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1.0
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
home:
  align: nsew
  argument: ''
  column: 1
  command: Home
  label: Home
  row: 4
  type: QPushButton
setpoint_value:
  column: 1
  command: SetPosition
  label: Setpoint [mm]
  row: 5
  type: QLineEdit
  value: 0.0
