device:
  name : DummyDataFreq
  label : Data Frequency
  path : test
  driver : DummyDataFreq
  constr_params : [period, frequency_span]
  meta_device : False
  correct_response : test
  slow_data : True
  row : 1
  column : 2
  max_nan_count : 10
  plots_queue_maxlen : 1000
  double_connect_dev : True

attributes:
  column_names : [time, frequency]
  units : [s, Hz]

period:
  type : dummy
  value : 10

frequency_span:
  type : dummy
  value : 50

enabled:
  label : Device enabled
  type : QCheckBox
  tristate : True
  row : 0
  col : 0
  value : 2

HDF_enabled:
  type : dummy
  value : 1

dt:
  label : Loop delay [s]
  type : QLineEdit
  row : 1
  col : 1
  value : 0.2
