device:
  name : histogram_plotter
  label : Histogram Plotter
  path : test/histogram
  driver : HistogramPlotter
  constr_params : [dev1, param1, processing, dev2, param2, lower, higher, width]
  meta_device : True
  correct_response : test
  slow_data : False
  row : 1
  column : 1
  max_nan_count : 10
  plots_queue_maxlen : 1000
  double_connect_dev : True

attributes:
  column_names : [frequency, integral]
  units : [MHz, adc]

enabled:
  label : Device enabled
  type : QCheckBox
  tristate : True
  row : 0
  col : 0
  value : 2

HDF_enabled:
  type : dummy
  value : 0

dt:
  label : Loop delay [s]
  type : QLineEdit
  row : 1
  col : 1
  value : 0.1

dev1:
  label : Dev1
  type : QLineEdit
  row : 2
  col : 1
  value : "DummyDataTrace"
  enter_cmd : SetDevice1

param1:
  label : Param1
  type : QLineEdit
  row : 2
  col : 2
  value : "ch2"
  enter_cmd : SetParam1

processing:
  label : Processing
  type : QLineEdit
  row : 2
  col : 3
  value : "-np.trapz(y[250:1900] - np.concatenate((y[50:200],y[-150:])).mean())"
  enter_cmd : SetProcessing

dev2:
  label : Dev2
  type : QLineEdit
  row : 3
  col : 1
  value : "DummyDataFreq"
  enter_cmd : SetDevice2

param2:
  label : Param2
  type : QLineEdit
  row : 3
  col : 2
  value : "frequency"
  enter_cmd : SetParam2

lower:
  label : Lower
  type : QLineEdit
  row : 4
  col : 1
  value : -50
  enter_cmd : SetLower

higher:
  label : higher
  type : QLineEdit
  row : 4
  col : 2
  value : 50
  enter_cmd : SetHigher

width:
  label : width
  type : QLineEdit
  row : 4
  col : 3
  value : 5
  enter_cmd : SetWidth
