COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: ASRL17::INSTR
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - compressor cabinet temp
  units:
  - s
  - C
device:
  column: 3
  constr_params:
  - COM_port
  correct_response: Beam Source Thermometer Arduino
  driver: Arduino
  label: Arduino
  max_nan_count: 10
  meta_device: false
  name: Arduino
  path: beam_source/pressure
  plots_queue_maxlen: 1000
  row: 2
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1.5
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 0
power_toggle:
  action_commands: ValveClose, ValveOpen
  argument: ''
  checked:
  - true
  - false
  - true
  - true
  colspan: 2
  column: 0
  label: (valve state?)
  monitoring_command: ValveStatus()
  return_values: opened, closed, invalid, None
  row: 4
  rowspan: 1
  states: enabled, disabled, error, disabled
  texts: Close valve, Open valve, (valve state?), (valve state?)
  type: indicator_button
