HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 0
InfluxDB_enabled:
  column: 0
  label: InfluxDB enabled
  row: 2
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - time delay
  units:
  - s
  - s
device:
  column: 0
  constr_params:
  - user
  - password
  correct_response: true
  driver: ClockSync
  label: Clock Sync
  max_nan_count: 10
  meta_device: false
  name: ClockSyncBeamsource
  path: timing
  plots_queue_maxlen: 1000
  row: 4
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 30
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 0
password:
  column: 2
  label: Password
  row: 3
  type: QLineEdit
  value: null
user:
  column: 1
  label: Username
  row: 3
  type: QLineEdit
  value: null
