COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: ASRL1::INSTR
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - cell back snorkel
  - 4K shield top
  - 40K shield top
  - 4K PT cold head
  - cell top plate
  - 4K shield bottom
  - 40K shield bottom
  - 16K PT cold head
  units:
  - s
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
device:
  column: 2
  constr_params:
  - COM_port
  correct_response: LSCI,MODEL218E,LSB2DW,041813
  driver: LakeShore218
  dt: 0.0
  enabled: 1
  label: LakeShore 218
  max_nan_count: 10
  meta_device: false
  name: L218
  path: beam_source/thermal
  plots_queue_maxlen: 1000
  row: 2
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 0.25
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
