COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: GPIB0::1::INSTR
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - voltage
  - current
  - power
  units:
  - s
  - V
  - A
  - W
current_indicator:
  column: 1
  command: SetCurrent
  label: Amps
  monitoring_command: MeasureCurrent()
  row: 5
  type: indicator_lineedit
  value: 0.0
device:
  column: 3
  constr_params:
  - COM_port
  correct_response: 0
  driver: HP6645A
  dt: 1.0
  enabled: 1
  label: 4K shield heaters
  max_nan_count: 10
  meta_device: false
  name: PS_4K
  path: beam_source/thermal
  plots_queue_maxlen: 1000
  row: 0
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1.0
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
output_toggle:
  action_commands: OutputDisable, OutputEnable
  argument: ''
  checked:
  - true
  - false
  - true
  - true
  colspan: 2
  column: 0
  label: '[output control state?]'
  monitoring_command: OutputStatusReport()
  return_values: on, off, invalid, None
  row: 6
  rowspan: 1
  states: enabled, disabled, error, disabled
  texts: Disable output, Enable output, [output control state?], [output control state?]
  type: indicator_button
voltage_indicator:
  column: 1
  command: SetVoltage
  label: Volts
  monitoring_command: MeasureVoltage()
  row: 4
  type: indicator_lineedit
  value: 0.0
