COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: 10.10.222.14
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - CoolantInTemp
  - CoolantOutTemp
  - OilTemp
  - HeliumTemp
  - LowPressure
  - LowPressureAverage
  - HighPressure
  - HighPressureAverage
  - DeltaPressureAverage
  - MotorCurrent
  units:
  - s
  - F
  - F
  - F
  - F
  - psi
  - psi
  - psi
  - psi
  - psi
  - amps
device:
  column: 0
  constr_params:
  - COM_port
  correct_response: 50306
  driver: CPA1110
  label: PT415
  max_nan_count: 10
  meta_device: false
  name: PT415
  path: beam_source/thermal
  plots_queue_maxlen: 1000
  row: 2
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1.0
enabled:
  colspan: null
  column: 0
  label: Device enabled
  row: 0
  rowspan: null
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
output_toggle:
  action_commands: DisableCompressor, EnableCompressor
  argument: ''
  checked:
  - true
  - false
  - true
  - true
  colspan: 2
  column: 0
  label: (compressor state?)
  monitoring_command: MotorStatus()
  return_values: running, stopped, accelerating, invalid, None
  row: 4
  rowspan: 1
  states: enabled, disabled, error, disabled
  texts: Stop compressor, Start compressor, Accelerating [press to start], (compressor
    speed?), (compressor speed?)
  type: indicator_button
