- - PMT HV
  - turn_on_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_on_ch1
  - null
  - 10.0
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointAGUI
  - 'args: [-2000,2000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-5000,0]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '16'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '1'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '2'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '3'
  - 5.0
  - false
  - null
  - true
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - true
  - []
- - FlowController
  - SetPointControl
  - '30'
  - 5.0
  - true
  - null
  - true
  - []
- - HVControlPos
  - EnableHV
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlNeg
  - EnableHV
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlPos
  - ramp_voltage
  - np.array([0,10,15,20,25,30])
  - null
  - false
  - null
  - true
  - - - HVControlNeg
      - ramp_voltage
      - $1
      - 10.0
      - false
      - null
      - true
      - []
    - - Laser Lock
      - move_laser2_lockpoint
      - ' 2159 + np.append(np.append(np.arange(0,5,1), np.arange(5,-5,-1)), np.arange(-5,0,1))'
      - 2.0
      - false
      - 1
      - true
      - - - PXIe5171
          - UpdateSequenceAttrs
          - parent_info
          - null
          - true
          - null
          - true
          - []
        - - PXIe5171
          - DummyFunc
          - '1'
          - 0.15
          - false
          - 10
          - true
          - - - YagIsolator
              - SetNrQswitchesGUI
              - '20'
              - null
              - false
              - null
              - true
              - []
            - - PXIe5171
              - ReadValue
              - null
              - null
              - true
              - 20
              - true
              - []
            - - ZaberTMM
              - randomStep
              - null
              - 0.5
              - false
              - null
              - true
              - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - true
  - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '16'
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch1
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlPos
  - ramp_voltage
  - '0'
  - null
  - false
  - null
  - true
  - []
- - HVControlNeg
  - ramp_voltage
  - '0'
  - 10.0
  - false
  - null
  - true
  - []
- - HVControlPos
  - DisableHV
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlNeg
  - DisableHV
  - null
  - null
  - false
  - null
  - true
  - []
