- - ZaberTMM
  - SetPointAGUI
  - 'args: [5000,5000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-2500,-5000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - true
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - true
  - []
- - FlowController
  - SetPointControl
  - '30'
  - 5.0
  - true
  - null
  - true
  - []
- - PXIe5171
  - DummyFunc
  - '1'
  - 0.15
  - false
  - 5
  - true
  - - - YagIsolator
      - SetNrQswitchesGUI
      - '30'
      - null
      - false
      - null
      - true
      - []
    - - PXIe5171
      - ReadValue
      - null
      - null
      - true
      - 30
      - true
      - []
    - - ZaberTMM
      - randomStep
      - null
      - 0.5
      - false
      - null
      - true
      - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - true
  - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - true
  - []
