- - ZaberTMM
  - SetPointAGUI
  - 'args: [-2000,4000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-3000,5000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '16'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '1'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '2'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '3'
  - 5.0
  - false
  - null
  - true
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - true
  - []
- - FlowController
  - SetPointControl
  - '30'
  - 5.0
  - true
  - null
  - true
  - []
- - Laser Lock 1
  - set_lockpoint_laser_2
  - 65 + np.append(np.arange(-14,14,2), np.arange(14,-14,-2))
  - 2.0
  - false
  - 4
  - true
  - - - PXIe5171
      - UpdateSequenceAttrs
      - parent_info
      - null
      - true
      - null
      - true
      - []
    - - PXIe5171
      - DummyFunc
      - '1'
      - 0.15
      - false
      - 5
      - true
      - - - YagIsolator
          - SetNrQswitchesGUI
          - '30'
          - null
          - false
          - null
          - true
          - []
        - - PXIe5171
          - ReadValue
          - null
          - null
          - true
          - 30
          - true
          - []
        - - ZaberTMM
          - randomStep
          - null
          - 0.5
          - false
          - null
          - true
          - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - true
  - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '16'
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch0
  - null
  - null
  - false
  - null
  - false
  - []
- - PMT HV
  - turn_off_ch1
  - null
  - null
  - false
  - null
  - false
  - []
