- - PMT HV
  - turn_on_ch0
  - null
  - 20.0
  - false
  - null
  - false
  - []
- - PMT HV
  - turn_on_ch1
  - null
  - 20.0
  - true
  - null
  - false
  - []
- - ZaberTMM
  - SetPointAGUI
  - 'args: [-4600,-4000]'
  - 0.1
  - false
  - null
  - false
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-5800,-2000]'
  - 0.1
  - false
  - null
  - false
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - false
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - false
  - []
- - Wavelength
  - SetPort
  - '1'
  - 5.0
  - false
  - null
  - false
  - []
- - Wavelength
  - SetPort
  - '2'
  - 5.0
  - false
  - null
  - false
  - []
- - Wavelength
  - SetPort
  - '3'
  - 5.0
  - false
  - null
  - false
  - []
- - Wavelength
  - SetPort
  - '16'
  - null
  - false
  - null
  - false
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - false
  - []
- - FlowController
  - SetPointControl
  - '30'
  - 5.0
  - true
  - null
  - false
  - []
- - SynthHD SPA
  - SetFrequencyCHAGUI
  - np.dstack([np.arange(-2,3,1), np.ones(5)*-100]).flatten()*1e6 + 13.34e9
  - 2.0
  - false
  - 1
  - true
  - - - PXIe5171
      - UpdateSequenceAttrs
      - parent_info
      - null
      - false
      - null
      - true
      - []
    - - PXIe5171
      - DummyFunc
      - '1'
      - null
      - false
      - 10
      - true
      - - - YagIsolator
          - SetNrQswitchesGUI
          - '10'
          - null
          - false
          - null
          - true
          - []
        - - PXIe5171
          - ReadValue
          - null
          - null
          - true
          - 10
          - true
          - []
        - - ZaberTMM
          - randomStep
          - null
          - 0.5
          - false
          - null
          - true
          - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - false
  - []
- - ZaberTMM
  - randomStep
  - null
  - 0.5
  - false
  - null
  - false
  - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - false
  - []
- - PMT HV
  - turn_off_ch1
  - null
  - null
  - false
  - null
  - false
  - []
- - PMT HV
  - turn_off_ch0
  - null
  - null
  - false
  - null
  - false
  - []
