- - PMT HV
  - turn_on_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_on_ch1
  - null
  - 10.0
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointAGUI
  - 'args: [-2000,2000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-5000,0]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - true
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - false
  - []
- - HVControlPos
  - EnableHV
  - null
  - null
  - false
  - null
  - false
  - []
- - HVControlNeg
  - EnableHV
  - null
  - null
  - false
  - null
  - false
  - []
- - FlowController
  - SetPointControl
  - '30'
  - null
  - false
  - null
  - false
  - []
- - Laser Lock
  - move_laser2_lockpoint
  - '2159'
  - 2.0
  - false
  - 1
  - false
  - []
- - PXIe5171
  - UpdateSequenceAttrs
  - parent_info
  - null
  - true
  - null
  - true
  - []
- - PXIe5171
  - DummyFunc
  - '1'
  - 0.15
  - false
  - 4
  - true
  - - - ZaberTMM
      - CreateWarning
      - '"D"'
      - 1.0
      - true
      - null
      - true
      - []
    - - PXIe5171
      - UpdateSequenceAttrs
      - parent_info
      - null
      - true
      - null
      - true
      - []
    - - PXIe5171
      - DummyFunc
      - '1'
      - 0.15
      - false
      - 10
      - true
      - - - HVControlPos
          - ramp_voltage
          - '0'
          - null
          - false
          - null
          - true
          - []
        - - HVControlNeg
          - ramp_voltage
          - '0'
          - 21.0
          - true
          - null
          - true
          - []
        - - YagIsolator
          - SetNrQswitchesGUI
          - '100'
          - null
          - false
          - null
          - true
          - []
        - - PXIe5171
          - ReadValue
          - null
          - null
          - true
          - 100
          - true
          - []
        - - HVControlPos
          - ramp_voltage
          - '30'
          - null
          - false
          - null
          - true
          - []
        - - HVControlNeg
          - ramp_voltage
          - '30'
          - 110.0
          - true
          - null
          - true
          - []
        - - YagIsolator
          - SetNrQswitchesGUI
          - '100'
          - null
          - false
          - null
          - true
          - []
        - - PXIe5171
          - ReadValue
          - null
          - null
          - true
          - 100
          - true
          - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch1
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlPos
  - ramp_voltage
  - '0'
  - null
  - false
  - null
  - true
  - []
- - HVControlNeg
  - ramp_voltage
  - '0'
  - 10.0
  - false
  - null
  - true
  - []
- - HVControlPos
  - DisableHV
  - null
  - null
  - false
  - null
  - true
  - []
- - HVControlNeg
  - DisableHV
  - null
  - null
  - false
  - null
  - true
  - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - true
  - []
