HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - ch1 voltage
  - Vd voltage
  - ch1 current
  - Vd current
  units:
  - s
  - V
  - V
  - I
  - I
device:
  column: 0
  constr_params:
  - resource
  correct_response: Siglent Technologies,SPD3303X-E,SPD3XIED5R7612,1.01.01.02.07R2,V3.0
  driver: SPD3303X
  label: +12V Vd -5V
  max_nan_count: 10
  meta_device: false
  name: 12pos_vd_5neg
  path: microwaves/
  plots_queue_maxlen: 1000
  row: 1
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 5
  width: 5
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
resource:
  column: 1
  command: ''
  label: Resource name
  options: ''
  row: 3
  type: QComboBox
  value: USB0::0xF4EC::0x1430::SPD3XIED5R7612::INSTR
