COM_port:
  colspan: null
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  rowspan: null
  tooltip: null
  type: QComboBox
  value: COM14
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - t1
  - t2
  - t3
  - t4
  - t5
  - t6
  - t7
  - t8
  - t9
  - t10
  - t11
  - t12
  - t13
  - t14
  - t15
  - t16
  - t17
  - t18
  - t19
  - t20
  units:
  - s
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
  - K
channels:
  col_labels: ', ch#'
  col_names: enable, channel
  col_options: '...; ...;'
  col_types: QCheckBox, QLabel
  col_values: 1, 0, 0, 0, 0, 0, 0, 0,0,0,0,0,0,0,0,0,0,0,0; t1, t2, t3, t4, t5, t6,
    t7, t9, t10, t11, t12, t13, t14, t15, t16, t17, t18, t19, t20;
  colspan: 1
  column: 1
  label: Channels
  row: 4
  row_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  rowspan: 4
  tooltip: null
  type: ControlsTable
device:
  column: 0
  constr_params:
  - COM_port
  - channels
  correct_response: true
  driver: ThermocoupleReadout
  label: Thermocouple
  max_nan_count: 10
  meta_device: false
  name: Thermocouple
  path: oven_test
  plots_queue_maxlen: 1000
  row: 2
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
