COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  type: QComboBox
  value: ASRL4::INSTR
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - wavemeter
  units:
  - s
  - GHz
device:
  column: 1
  columnspan: 1
  constr_params:
  - COM_port
  correct_response: todo
  driver: WA1500
  label: Burleigh WA-1500
  monitoring_column: 0
  monitoring_row: 2
  name: WA1500
  path: readout
  plots_queue_maxlen: 1000
  row: 1
  rowspan: 1
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 0.2
  width: 5
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
units:
  align: w
  argument: ''
  column: 1
  command: Units
  label: Change units
  row: 4
  type: QPushButton
