[[PXIe5171, DummyFunc, 1, 0.15, false, 10, true, [[YagIsolator, SetNrQswitchesGUI,
        10, null, false, null, true, []], [PXIe5171, ReadValue, null, null, true,
        10, true, []], [ZaberTMM, nextStep, null, null, false, null, true, []]]]]
