COM_port:
  colspan: null
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 3
  rowspan: null
  tooltip: null
  type: QComboBox
  value: PXI1Slot2
HDF_enabled:
  colspan: null
  column: 0
  label: HDF enabled
  row: 1
  rowspan: null
  tooltip: null
  type: QCheckBox
  value: true
attributes:
  column_names:
  - ch2
  units:
  - binary
channels:
  col_labels: ', ch#, Range, Coupling'
  col_names: enable, channel, range, coupling
  col_options: '...; ...; 0.2 V, 0.4 V, 1 V, 2 V, 5 V; DC, AC, GND'
  col_types: QCheckBox, QLabel, QComboBox, QComboBox
  col_values: 1, 1, 0, 0, 0, 0, 0, 0; 0, 1, 2, 3, 4, 5, 6, 7; 5 V, 5 V, 2 V, 5 V,
    1 V, 2 V, 1 V, 1 V; DC, DC, DC, DC, DC, DC, DC, DC
  colspan: 1
  column: 1
  label: Channels
  row: 4
  row_ids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  rowspan: 4
  tooltip: null
  type: ControlsTable
device:
  column: 0
  constr_params:
  - COM_port
  - record
  - sample
  - trigger
  - edge
  - channels
  correct_response: not implemented
  driver: PXIe5171
  label: NI PXIe-5171
  max_nan_count: 0
  meta_device: false
  name: PXIe5171
  path: readout/PXIe-5171
  plots_fn: 'y * self.dset_attrs[-1][self.config["y"].strip()+" : gain"] + self.dset_attrs[-1][self.config["y"].strip()+"
    : offset"]'
  plots_queue_maxlen: 1000
  row: 0
  slow_data: false
dt:
  colspan: null
  column: 1
  command: null
  label: Loop delay [s]
  row: 2
  rowspan: null
  tooltip: null
  type: QLineEdit
  value: 0.01
edge:
  colspan: null
  column: 0
  ctrl_labels: Source, Slope, Level
  ctrl_names: trigger_src, trigger_slope, trigger_level
  ctrl_options: 0, 1, 2, 3, 4, 5, 6, 7; Rising, Falling; ...
  ctrl_types: QComboBox, QComboBox, QLineEdit
  ctrl_values: 0, Rising, 0.5
  label: Edge
  row: 7
  rowspan: null
  tooltip: null
  type: ControlsRow
enabled:
  colspan: null
  column: 0
  label: Device enabled
  row: 0
  rowspan: null
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 1
record:
  colspan: null
  column: 0
  ctrl_labels: Length, BW [MHz], nr_records
  ctrl_names: record_length, bandwidth_MHz, nr_records
  ctrl_options: '...; 100, 270; ...'
  ctrl_types: QLineEdit, QComboBox, QLineEdit
  ctrl_values:
  - 2000
  - 100.0
  - 1
  label: Record
  row: 4
  rowspan: null
  tooltip: null
  type: ControlsRow
sample:
  colspan: null
  column: 0
  ctrl_labels: Sample rate [kS/s], Sample width [bits]
  ctrl_names: sample_rate, sample_width
  ctrl_options: '...; 8, 16, 32'
  ctrl_types: QLineEdit, QComboBox
  ctrl_values:
  - 100
  - 16
  label: Sample
  row: 5
  rowspan: null
  tooltip: null
  type: ControlsRow
trigger:
  colspan: null
  column: 0
  ctrl_labels: Type, Delay
  ctrl_names: trigger_type, trigger_delay
  ctrl_options: Edge, Immediate; ...
  ctrl_types: QComboBox, QLineEdit
  ctrl_values: Edge, 0.00
  label: Trigger
  row: 6
  rowspan: null
  tooltip: null
  type: ControlsRow
