[[PXIe5171, DummyFunc, 'np.linspace(0,2,3)', 5, false, null, true, [[PXIe5171, UpdateSequenceAttrs,
        parent_info, 0, false, null, true, []], [PXIe5171, ReadValue, null, 0, false,
        5, true, []]]], [PXIe5171, DummyFunc, 'np.linspace(0,2,3)', 5, false, null,
    true, [[PXIe5171, UpdateSequenceAttrs, parent_info, 0, false, null, true, []],
      [PXIe5171, ReadValue, null, 0, false, 5, true, []]]]]
