COM_port_fiberswitch:
  column: 1
  label: Fiber Switch
  row: 5
  type: QLineEdit
  value: COM23
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: false
Set_port:
  colspan: null
  column: 1
  command: SetPort
  label: Port
  options:
  - 1
  - 2
  - 3
  - 16
  row: 6
  rowspan: null
  tooltip: null
  type: QComboBox
  value: 1
attributes:
  column_names:
  - time
  - seed1
  - seed2
  - seed3
  - cesium
  - power
  - temperature
  - pressure
  units:
  - s
  - THz
  - THz
  - THz
  - THz
  - mW
  - C
  - mm Hg
connection_wavemeter:
  column: 1
  ctrl_labels: IP, Port
  ctrl_names: telnet_address, telnet_port
  ctrl_options: '...; ...'
  ctrl_types: QLineEdit, QLineEdit
  ctrl_values: 10.10.222.7, 23
  label: Wavemeter
  row: 4
  type: ControlsRow
device:
  column: 0
  constr_params:
  - connection_wavemeter
  - COM_port_fiberswitch
  - ports
  correct_response: BRISTOL WAVELENGTH METER, 671A-VIS, 6894, 1.2.1, True
  driver: WavemeterFiberswitch
  label: Wavemeter + Switch Server
  max_nan_count: 0
  meta_device: false
  name: Wavemeter + Switch Server
  path: lasers
  plots_queue_maxlen: 1000
  row: 0
  slow_data: true
driver:
  type: dummy
  value: ''
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 0.5
  width: 5
enabled:
  colspan: null
  column: 0
  label: Device enabled
  row: 0
  rowspan: null
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
port:
  column: 1
  label: Socket Port
  row: 3
  type: QLineEdit
  value: 65431
ports:
  type: dummy
  value:
  - 1
  - 2
  - 3
  - 16
timeout:
  type: dummy
  value: 0.5
