[device]
name = Laser Lock
label = Laser Lock
path = lasers
driver = LaserLockCompatible
constr_params = address, port_api
correct_response = LASERLOCK_EXPERIMENT_CONTROL
slow_data = True
row = 3
column = 0
plots_queue_maxlen = 1000
max_NaN_count = 0
meta_device = False
compound_dataset = True
double_connect_dev = True

; [attributes]
; column_names = time, lock, error mean, error std, control mean, emission, frequency, frequency setpoint, power, nltl frequency, nltl power
; units = s, , , , , , Hz, Hz, mW, Hz, dBm
[attributes]
column_names = time,RC nltl enable,RC nltl frequency,RC nltl frequency setpoint,RC nltl power,ABS nltl enable,ABS nltl frequency,ABS nltl frequency setpoint,ABS nltl power,DET1 nltl enable,DET1 nltl frequency,DET1 nltl frequency setpoint,DET1 nltl power
units = s,,MHz,MHz,dBm,,MHz,MHz,dBm,,MHz,MHz,dBm

[enabled]
label = Enabled
type = QCheckBox
tristate = True
row = 0
col = 0
tooltip = None
rowspan = None
colspan = None
value = 2

[HDF_enabled]
label = HDF
type = QCheckBox
row = 1
col = 0
tooltip = None
rowspan = None
colspan = None
value = True


; [Set_Transition]
; label = Set_Transition
; type = QComboBox
; row = 3
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = R0F2
; options = R0F2, R1F3, R2F4
; command = switch_transitions

; [set_R0F2_piezo_voltage]
; label = set_R0F2_piezo_voltage [V]
; type = QLineEdit
; row = 4
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = 0.901
; enter_cmd = set_R0F2_piezo_voltage

; [set_R1F3_piezo_voltage_pos]
; label = set_R1F3_piezo_voltage_pos [V]
; type = QLineEdit
; row = 5
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = -0.072
; enter_cmd = set_R1F3_piezo_voltage_pos

; [set_R1F3_piezo_voltage_neg]
; label = set_R1F3_piezo_voltage_neg [V]
; type = QLineEdit
; row = 6
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = 0.05
; enter_cmd = set_R1F3_piezo_voltage_neg


; [set_R2F4_piezo_voltage]
; label = set_R2F4_piezo_voltage [V]
; type = QLineEdit
; row = 7
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = -0.861
; enter_cmd = set_R2F4_piezo_voltage


; [wavemeter_offset]
; label = wavemeter_offset [GHz]
; type = QLineEdit
; row = 8
; col = 1
; tooltip = None
; rowspan = 1
; colspan = 1
; value = 0.030
; enter_cmd = set_wavemeter_offset


[dt]
label = Loop delay [s]
type = QLineEdit
row = 2
col = 1
tooltip = None
rowspan = None
colspan = None
value = 1.0
enter_cmd = None

[address]
type = dummy
value = "10.10.222.31"

[port_api]
type = dummy
value = 8001
