HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: true
attributes:
  column_names:
  - time
  - microwave power
  - laser power
  units:
  - s
  - dBm
  - A
device:
  column: 0
  constr_params:
  - microwave
  - microwave_cmd
  - microwave_powers
  - microwave_power_low
  - microwave_frequency
  - microwave_time_step
  - laser
  - laser_cmd
  - laser_powers
  - wait_time
  correct_response: sweep
  driver: J1J2MicrowaveMeasurementControl
  label: J1->J2 Power Sweep
  max_nan_count: 0
  meta_device: true
  name: J1J2MeasurementControl
  path: readout
  plots_queue_maxlen: 1000
  row: 3
  slow_data: true
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 0.1
  width: 5
enabled:
  colspan: null
  column: 0
  label: Device enabled
  row: 0
  rowspan: null
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
laser:
  type: dummy
  value: Seed1Amplifier
laser_cmd:
  type: dummy
  value: SetCurrent(arg)
laser_powers:
  type: dummy
  value:
  - 3.5
  - 4.3
  - 5
  - 5.5
  - 6
  - 6.5
microwave:
  type: dummy
  value: SynthHDPro
microwave_cmd:
  type: dummy
  value: SetPowerGUI(arg)
microwave_frequency:
  type: dummy
  value: 13334500000.0
microwave_power_low:
  type: dummy
  value: -30
microwave_powers:
  type: dummy
  value:
  - -18.5
  - -17.5
  - -17
  - -16.5
  - -15.9
  - -14.5
  - -13.8
  - -10
microwave_time_step:
  type: dummy
  value: 2
start_sweep:
  action_commands: StopSweep, StartSweep
  argument: ''
  checked:
  - true
  - false
  - false
  colspan: 1
  column: 1
  label: (sweep?)
  monitoring_command: GetSweepStatus()
  return_values: Sweeping, Inactive, invalid
  row: 3
  rowspan: 1
  states: enabled, disabled, error, disabled
  texts: Sweeping, Inactive , (?)
  tooltip: Start/Stop sweep
  type: indicator_button
wait_time:
  type: dummy
  value: 300
