[[ZaberTMM, SetPointAGUI, 'args: [1,1]', 0.1, false, null, true, []], [ZaberTMM, SetPointBGUI,
    'args: [-2500,5000]', 0.1, false, null, true, []], [ZaberTMM, SetStepGUI, 25,
    0.1, false, null, true, []], [ZaberTMM, setupStepRectangle, null, 0.1, false,
    null, true, []], [FlowController, SetPointControl, 30, 5, true, null, true, []],
  [Laser Lock 2, SetLockPointSeed1, '140 + np.append(np.arange(0,500,10), np.arange(500,0,-10))',
    2, false, 1, true, [[PXIe5171, UpdateSequenceAttrs, parent_info, null, false,
        null, true, []], [PXIe5171, DummyFunc, 1, 0.15, false, 4, true, [[YagIsolator,
            SetNrQswitchesGUI, 10, null, false, null, true, []], [PXIe5171, ReadValue,
            null, null, true, 10, true, []], [ZaberTMM, randomStep, null, 0.5, false,
            null, true, []]]]]], [FlowController, SetPointControl, 0, null, false,
    null, true, []]]
