COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 4
  type: QComboBox
  value: COM10
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: false
InfluxDB_enabled:
  column: 0
  label: InfluxDB enabled
  row: 2
  type: QCheckBox
  value: 0
attributes:
  column_names:
  - time
  - temperature_cooling_group
  - voltage
  - pump
  - laser
  units:
  - s
  - C
  - V
  - ''
device:
  column: 0
  compound_dataset: false
  constr_params:
  - COM_port
  correct_response: '062'
  driver: BigSkyYag
  label: BigSkyYag
  max_nan_count: 0
  meta_device: false
  name: BigSkyYag
  path: lasers
  plots_queue_maxlen: 1000
  row: 1
  slow_data: true
dt:
  column: 1
  command: null
  label: Loop delay [s]
  row: 2
  tooltip: null
  type: QLineEdit
  value: 5
enabled:
  column: 0
  label: Device enabled
  row: 0
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
pump_control:
  action_commands: stop_pump, start_pump
  argument: ''
  checked:
  - true
  - false
  colspan: 1
  column: 1
  label: (pump?)
  monitoring_command: status_pump()
  return_values:
  - true
  - false
  row: 5
  rowspan: 1
  states: enabled, disabled
  texts: Stop pump, Start pump
  type: indicator_button
yag_control:
  action_commands: stop, start
  argument: ''
  checked:
  - true
  - false
  colspan: 1
  column: 2
  label: (active?)
  monitoring_command: status_string()
  return_values:
  - true
  - false
  row: 5
  rowspan: 1
  states: enabled, disabled
  texts: Stop YAG, Start YAG
  type: indicator_button
