[
  [ZaberTMM, SetPointAGUI, "args: [1,1]", 0.1, false, null, true, []],
  [ZaberTMM, SetPointBGUI, "args: [-2500,5000]", 0.1, false, null, true, []],
  [ZaberTMM, SetStepGUI, 25, 0.1, false, null, true, []],
  [ZaberTMM, setupStepRectangle, null, 0.1, false, null, true, []],
  [Wavelength, SetPort, 3, 5, false, null, true, []],
  [Wavelength, SetPort, 2, 5, false, null, true, []],
  [Wavelength, SetPort, 1, 5, false, null, true, []],
  [Wavelength, SetPort, 16, null, false, null, true, []],
  [BigSkyYag, start, null, null, false, null, true, []],
  [FlowController, SetPointControl, 30, 5, true, null, true, []],
  [
    Polarization SDG1032X,
    SetChannel1Frequency,
    "np.append(np.linspace(0,1.5e6,7),
    np.linspace(1.5e6, 0, 7))",
    2,
    false,
    2,
    true,
    [
      [PXIe5171, UpdateSequenceAttrs, parent_info, null, false, null, true, []],
      [
        PXIe5171,
        DummyFunc,
        1,
        0.15,
        false,
        15,
        true,
        [
          [YagIsolator, SetNrQswitchesGUI, 20, null, false, null, true, []],
          [PXIe5171, ReadValue, null, null, true, 20, true, []],
          [ZaberTMM, randomStep, null, 0.5, false, null, true, []],
        ],
      ],
    ],
  ],
  [FlowController, SetPointControl, 0, null, false, null, true, []],
  [BigSkyYag, stop, null, null, false, null, true, []],
]
