[[PMT HV, turn_on_ch0, null, null, false, null, true, []], [PMT HV, turn_on_ch1, null,
    null, false, null, true, []], [ZaberTMM, SetPointAGUI, 'args: [2400,-7500]', 0.1,
    false, null, true, []], [ZaberTMM, SetPointBGUI, 'args: [0,-9000]', 0.1, false,
    null, true, []], [ZaberTMM, SetStepGUI, 25, 0.1, false, null, true, []], [ZaberTMM,
    setupStepRectangle, null, 0.1, false, null, true, []], [Wavelength, SetPort, 16,
    5, false, null, true, []], [Wavelength, SetPort, 1, 5, false, null, true, []],
  [Wavelength, SetPort, 2, 5, false, null, true, []], [Wavelength, SetPort, 3, 5,
    false, null, true, []], [BigSkyYag, start, null, null, false, null, true, []],
  [FlowController, SetPointControl, 30, 5, true, null, true, []], [Laser Lock 1, set_lockpoint_laser_2,
    '-183 + np.append(np.arange(-15,15,2), np.arange(15,-15,-2))', 2, false, 1, true,
    [[PXIe5171, UpdateSequenceAttrs, parent_info, null, true, null, true, []], [PXIe5171,
        DummyFunc, 1, 0.15, false, 2, true, [[YagIsolator, SetNrQswitchesGUI, 20,
            null, false, null, true, []], [PXIe5171, ReadValue, null, null, true,
            20, true, []], [ZaberTMM, randomStep, null, 0.5, false, null, true, []]]]]],
  [FlowController, SetPointControl, 0, null, false, null, true, []], [BigSkyYag, stop,
    null, null, false, null, true, []], [Wavelength, SetPort, 16, null, false, null,
    true, []], [PMT HV, turn_off_ch0, null, null, false, null, true, []], [PMT HV,
    turn_off_ch1, null, null, false, null, true, []], [BigSkyYag, stop, null, null,
    false, null, true, []]]
