- - PMT HV
  - turn_on_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_on_ch1
  - null
  - null
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointAGUI
  - 'args: [-3000,0]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetPointBGUI
  - 'args: [-4000,1000]'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - SetStepGUI
  - '25'
  - 0.1
  - false
  - null
  - true
  - []
- - ZaberTMM
  - setupStepRectangle
  - null
  - 0.1
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '1'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '2'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '3'
  - 5.0
  - false
  - null
  - true
  - []
- - Wavelength
  - SetPort
  - '16'
  - null
  - false
  - null
  - true
  - []
- - BigSkyYag
  - start
  - null
  - null
  - false
  - null
  - true
  - []
- - FlowController
  - SetPointControl
  - '30'
  - 5.0
  - true
  - null
  - true
  - []
- - SynthHD SPA
  - SetPowerCHBGUI
  - np.linspace(-15,0,6)
  - 2.0
  - false
  - null
  - true
  - - - SynthHD SPA
      - SetFrequencyCHBGUI
      - np.linspace(-0.9,0.9,13)*1e6 + 13334190000.0
      - 0.1
      - false
      - 1
      - true
      - - - PXIe5171
          - DummyFunc
          - np.array([0])
          - null
          - false
          - 5
          - true
          - - - SynthHD SPA
              - SetFrequencyCHBGUI
              - $2
              - 2.0
              - false
              - null
              - true
              - []
            - - PXIe5171
              - UpdateSequenceAttrs
              - parent_info
              - null
              - false
              - null
              - true
              - []
            - - YagIsolator
              - SetNrQswitchesGUI
              - '15'
              - null
              - false
              - null
              - true
              - []
            - - PXIe5171
              - ReadValue
              - null
              - null
              - true
              - 15
              - true
              - []
            - - SynthHD SPA
              - SetFrequencyCHBGUI
              - np.array([13334190000.0-50e6])
              - 2.0
              - false
              - null
              - true
              - []
            - - PXIe5171
              - DummyFunc
              - np.array([-50])
              - null
              - false
              - null
              - true
              - - - PXIe5171
                  - UpdateSequenceAttrs
                  - parent_info
                  - null
                  - false
                  - null
                  - true
                  - []
                - - YagIsolator
                  - SetNrQswitchesGUI
                  - '15'
                  - null
                  - false
                  - null
                  - true
                  - []
                - - PXIe5171
                  - ReadValue
                  - null
                  - null
                  - true
                  - 15
                  - true
                  - []
            - - ZaberTMM
              - randomStep
              - null
              - 0.5
              - false
              - null
              - true
              - []
- - FlowController
  - SetPointControl
  - '0'
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch0
  - null
  - null
  - false
  - null
  - true
  - []
- - PMT HV
  - turn_off_ch1
  - null
  - null
  - false
  - null
  - true
  - []
- - ZaberTMM
  - randomStep
  - null
  - 0.5
  - false
  - null
  - true
  - []
- - BigSkyYag
  - stop
  - null
  - null
  - false
  - null
  - true
  - []
