COM_port:
  type: dummy
  value: client
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: true
attributes:
  column_names:
  - time
  - j12 frequency
  - j23 frequency
  - j12 power
  - j23 power
  - j12 status
  - j23 status
  units:
  - s
  - Hz
  - Hz
  - dB
  - dB
  - ''
  - ''
connection:
  type: dummy
  value:
    device_name: SynthHD Pro
    port_control: '12346'
    port_readout: '12345'
    publisher_name: Rotational Cooling Microwaves
    server: 10.10.222.13
device:
  column: 1
  compound_dataset: true
  constr_params:
  - driver
  - connection
  - COM_port
  correct_response: true
  driver: NetworkingClient
  label: SynthHD RC
  max_nan_count: 5
  meta_device: false
  name: SynthHD RC
  path: microwaves/
  plots_queue_maxlen: 1000
  row: 4
  slow_data: true
driver:
  type: dummy
  value: SynthHDPro
dt:
  column: 1
  command: null
  label: Loop delay [s]
  row: 2
  tooltip: null
  type: QLineEdit
  value: 1
enabled:
  column: 0
  label: Device enabled
  row: 0
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
