HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  type: QCheckBox
  value: 1
attributes:
  column_names:
  - time
  - flow signal
  - setpoint value
  units:
  - s
  - sccm
  - sccm
change_setpoint:
  align: nsew
  argument: setpoint_value
  column: 2
  command: SetPointControl
  label: Set
  row: 3
  type: QPushButton
connection:
  type: dummy
  value:
    device_name: USB6008
    port_control: '12347'
    port_readout: '12346'
    publisher_name: BeamsourceControl
    server: 10.10.222.12
device:
  column: 1
  constr_params:
  - driver
  - connection
  correct_response: operational
  driver: NetworkingClient
  label: Flow Controller
  max_nan_count: 10
  meta_device: false
  name: FlowController
  path: beam_source/gas
  plots_queue_maxlen: 1000
  row: 0
  slow_data: true
driver:
  type: dummy
  value: USB6008
dt:
  column: 1
  label: Loop delay [s]
  row: 2
  type: QLineEdit
  value: 1.0
enabled:
  column: 0
  label: Device enabled
  row: 0
  tristate: true
  type: QCheckBox
  value: 2
neon_indicator:
  colspan: 2
  column: 0
  label: (neon status?)
  monitoring_command: NeonStatus()
  return_values: flowing, not flowing, invalid, None
  row: 9
  rowspan: 1
  states: enabled, disabled, error, disabled
  texts: Flowing, Not flowing, (neon status?), (neon status?)
  tooltip: null
  type: indicator
setpoint_value:
  column: 1
  command: SetPointControl
  label: Setpoint [sccm]
  row: 3
  type: QLineEdit
  value: 0.0
