COM_port:
  column: 1
  command: ''
  label: COM port
  options: ''
  row: 4
  type: QComboBox
  value: COM8
HDF_enabled:
  column: 0
  label: HDF enabled
  row: 1
  tooltip: null
  type: QCheckBox
  value: true
InfluxDB_enabled:
  column: 0
  label: InfluxDB enabled
  row: 2
  type: QCheckBox
  value: 0
attributes:
  column_names:
  - time
  - position
  units:
  - s
  - mm
device:
  column: 1
  constr_params:
  - COM_port
  correct_response: YAG Lens Stage
  driver: YagLensStage
  label: Yag Lens Stage
  max_nan_count: 10
  meta_device: false
  name: YagLensStage
  path: lasers
  plots_queue_maxlen: 1000
  row: 2
  slow_data: true
dt:
  column: 1
  command: null
  label: Loop delay [s]
  row: 2
  tooltip: null
  type: QLineEdit
  value: 1
enabled:
  column: 0
  label: Device enabled
  row: 0
  tooltip: null
  tristate: true
  type: QCheckBox
  value: 2
